[project]
name = "DirectusPyWrapper"
version = "0.0.1"
dynamic = ["dependencies"]
authors = [
    { name = "Panos Stavrianos" }
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }


